apiVersion: v1
kind: Service
metadata:
  name: pythonbackend
spec:
  ports:
  - port: 5000
  type: LoadBalancer
  selector:
    app: pythonbackend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonbackend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pythonbackend
  template:
    metadata:
      labels:
        app: pythonbackend
    spec:
      containers:
      - name: pythonbackend
        image: pythonbackend
        ports:
        - containerPort: 5000